version: '3'
services:
  node:
    build:
      context: ./
      dockerfile: Node.Dockerfile
    ports:
      - '5000:5000'
    volumes:
      - $PWD:/code
  mariadb:
    build:
      context: ./
      dockerfile: MariaDB.Dockerfile
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    restart: always
