services:
    Cakes.domain.CakeRepository:
        class: ../../../BoundedContext/Cakes/infrastructure/MariadbCakeRepository
        arguments: ['']

    Cakes.application.CakeCreator:
        class: ../../../BoundedContext/Cakes/application/CakeCreator
        arguments: ['@Cakes.domain.CakeRepository']

    Cakes.application.CakeUpdater:
        class: ../../../BoundedContext/Cakes/application/CakeUpdater
        arguments: ['@Cakes.domain.CakeRepository']
